version: '3.3'

volumes:
  redis_data:
    driver: local

services:
  db:
    image: go-db:${P3_DB_VERSION}
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${APPLICATION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${APPLICATION_POSTGRES_PW}
      DB_NAME: ${DATA_SERVICE_POSTGRES_DB}
      DB_USER: ${DATA_SERVICE_POSTGRES_USER}
      DB_PASS: ${DATA_SERVICE_POSTGRES_PW}

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "3030:6379"
    volumes:
      - 'redis_data:/bitnami'

  redis-stat:
    image: insready/redis-stat:latest
    env_file:
      - .env
    restart: always
    ports:
      - "63790:63790"
    links:
      - redis:redis
    command: -v --auth=${REDIS_PASSWORD} --server redis=63790
    depends_on:
      - redis
