#!/bin/bash
#set -e

POSTGRES="psql --username ${APPLICATION_POSTGRES_USER}"

echo "Creating database: ${DB_NAME}"

$POSTGRES <<EOSQL
CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};

ALTER ROLE ${DB_USER} INHERIT;
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};

EOSQL